name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: npm ci
    - name: Run tests
      run: npm run test